name: cathay
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - intel-openmp=2021.3.0
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1k
  - pandas=1.2.5
  - pip=21.1.3
  - python=3.7.10
  - python-dateutil=2.8.2
  - pytz=2021.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
